export enum RolePermissionName {
  ADMIN_READ_USER = 'ADMIN_READ_USER',
  ADMIN_CREATE_USER = 'ADMIN_CREATE_USER',
  ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER',
  ADMIN_DELETE_USER = 'ADMIN_DELETE_USER',

  NUTRITION_ACCESS = 'NUTRITION_ACCESS',
  WORKOUT_ACCESS = 'WORKOUT_ACCESS',

  CREATE_MEAL = 'CREATE_MEAL',
  READ_MEAL = 'READ_MEAL',
  UPDATE_MEAL = 'UPDATE_MEAL',
  DELETE_MEAL = 'DELETE_MEAL',
  GUEST = 'GUEST',
}
